;----------Below variables are User modifiable  ---------------------------------------------------                                                                                                   

# OUtputDest  - set the location of result in which temperaure value has been stored with graph 

;************************************************************************************************
#  Note:  BaseFile should always be placed in the same diretory where all the other files are saved |
;************************************************************************************************

[PATH]

Result = F:\Rio Tinto Full\Rio_tinto_2.5M_Stright WG\Trial_1\Result_test
# Amplitude_Threshold   -  The minimum aplitude value from which we can detect peak.  
# samplefreq_in_MHz     -  defines the sampling frequency of the signal generator
# Distance            - Distance between the notchs (Gauge Distance in terms of data points)
# Trigger          -  Initial Signal before notch
 
[THRESHOLDS]

samplefreq_in_MHz = 250

#CONSTANTS LEFT & Right

# Alpha - Coefficient of Linear Thermal Expansion
# L0_1 - Gauge length of 1st sensor at T0
# L0_2 - Gauge length of 3nd sensor at T0
# L0_3 - Gauge length of 5rd sensor at T0
# L0_4 - Gauge length of 7nd sensor at T0
# L0_5 - Gauge length of 9rd sensor at T0
# T0 - Initial Room Temperature

[CONSTANTS]

Alpha = 0.0000172

L0_1 = 148680
L0_2 = 24280
L0_3 = 22000
L0_4 = 26760
#L0_5 = 83715

T0 = 27


#VELOCITY COEFFICIENTS Left & Right
 
# M   -  defines coefficient of x^2 value   in velocity equation
# N   -  defines coefficient of x value   in velocity equation
# P -  defines constant coefficient value in velocity equation

[VELOCITY COEFFICIENTS]

M1 = -0.000188
N1 = -0.368678
P1 = 3100.333699

M2 = -0.000156609
N2 = -0.365214699
P2 = 3064.395806403

[SHEAR VELOCITY COEFFICIENTS]

S_M1 = -0.000153
S_N1 = -0.385108
S_P1 = 3103.123781

S_L1 = 11051
S_L2 = 14851
S_L3 = 20051


